version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    volumes: []
      # - C:/Users/user/CascadeProjects/portfolio-bts-sio-sisr-master/src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Blackxender180901!
      MYSQL_DATABASE: portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: Blackxender180901!
    volumes:
      # - C:/Users/user/CascadeProjects/portfolio-bts-sio-sisr-master/database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
